# -*- coding: utf-8 -*-
"""Petites phrases humour / spécialités locales (FR/EN) par code pays. Ton pro mais décontracté."""

# Fallback : (fr, en)
GENERIC_TIPS = [
    ("Rapportez au moins une spécialité locale. Les collègues vous pardonneront le retard.", "Bring back at least one local treat. Colleagues will forgive the delay."),
    ("Un selfie devant le monument le plus kitsch du pays. Pour la postérité.", "A selfie in front of the tackiest landmark. For posterity."),
    ("Goûtez au plat que les locaux mangent au petit-déj. Game changer.", "Try what the locals eat for breakfast. Game changer."),
    ("Un souvenir qui tient dans le bagage cabine. Les douanes vous remercient.", "A souvenir that fits in your carry-on. Customs will thank you."),
    ("Trouvez le café / thé local. Votre réunion de 8h vous remerciera.", "Find the local coffee or tea. Your 8am meeting will thank you."),
    ("Rapportez une bouteille. Pas forcément d'alcool. Une sauce, un sirop…", "Bring back a bottle. Doesn't have to be alcohol. A sauce, syrup…"),
    ("Un marché local > un centre commercial. Toujours.", "A local market > a shopping mall. Always."),
    ("Prenez une photo du plat le plus bizarre que vous osez commander.", "Snap a photo of the weirdest dish you dare to order."),
    ("Une spécialité sucrée à rapporter. Le bureau vote.", "A local sweet to bring back. The office votes."),
    ("Le meilleur souvenir ? Ce que vous ne pouvez pas acheter à l'aéroport.", "Best souvenir? Something you can't buy at the airport."),
    ("Un fromage, une épice ou un alcool local. Les douanes autorisent (vérifiez).", "Local cheese, spice or spirit. Customs allow (check first)."),
    ("Goûtez au fast-food local. Souvent surprenant.", "Try the local fast food. Often surprising."),
    ("Rapportez une carte postale. L'art du retro n'est pas mort.", "Bring back a postcard. Retro isn't dead."),
    ("Un dessert typique. Les calories en déplacement ne comptent pas.", "A typical dessert. Travel calories don't count."),
    ("Trouvez le spot photo que les locaux utilisent. Pas celui de TripAdvisor.", "Find the photo spot the locals use. Not the TripAdvisor one."),
]

# Spécialités / humour par code — nourriture, à rapporter, truc à faire, cliché sympa
SPECIFIC_TIPS = {
    "AD": ("Ski et thermalisme. Rapportez du fuet si vous aimez le saucisson.", "Ski and spas. Bring back fuet if you're into cured sausage."),
    "AE": ("Dattes et or. Rapportez des dattes (plus léger). Et un selfie au Burj.", "Dates and gold. Bring back dates (lighter). And a Burj selfie."),
    "AF": ("Contexte exigeant : priorité sécurité. Un jour, le tourisme reviendra.", "Challenging context — safety first. One day tourism will return."),
    "AG": ("Rum punch et plage. Rapportez du rhum antillais (en soute).", "Rum punch and beach. Bring back Caribbean rum (in hold)."),
    "AL": ("Raki, byrek et côte. Rapportez de l'huile d'olive ou du miel.", "Raki, byrek and coast. Bring back olive oil or honey."),
    "AM": ("Cognac arménien (oui, ça existe) et lavash. Les amis seront impressionnés.", "Armenian cognac (yes, it exists) and lavash. Friends will be impressed."),
    "AO": ("Café angolais et piri-piri. Rapportez du piri-piri pour les barbecues.", "Angolan coffee and piri-piri. Bring back piri-piri for BBQs."),
    "AR": ("Malbec, dulce de leche et steak. La valise sentira bon au retour.", "Malbec, dulce de leche and steak. Your suitcase will smell great."),
    "AT": ("Sachertorte, schnaps et Tyrol. Rapportez du Mozartkugel. Ou deux.", "Sachertorte, schnaps and Tyrol. Bring back Mozartkugel. Or two."),
    "AU": ("Vegemite (osez), Tim Tam et barbie. Rapportez du Tim Tam pour le bureau.", "Vegemite (dare you), Tim Tam and barbie. Bring back Tim Tam for the office."),
    "AZ": ("Thé et grenade (le fruit). Rapportez du caviar ou de la confiture de grenade.", "Tea and pomegranate. Bring back caviar or pomegranate jam."),
    "BA": ("Ćevapi, café turc et pont de Mostar. Rapportez de la rakija (avec modération).", "Ćevapi, Turkish coffee and Mostar bridge. Bring back rakija (in moderation)."),
    "BB": ("Rum, flying fish et Rihanna. Rapportez du rhum Mount Gay.", "Rum, flying fish and Rihanna. Bring back Mount Gay rum."),
    "BD": ("Thé et curry. Rapportez du sari ou des épices si la valise le permet.", "Tea and curry. Bring back a sari or spices if the bag allows."),
    "BE": ("Frites, bière et chocolat. Rapportez des pralines. Pas une seule boîte.", "Fries, beer and chocolate. Bring back pralines. More than one box."),
    "BF": ("Poulet bicyclette et dolo. Rapportez du beurre de karité (cosmétique ou cuisine).", "Poulet bicyclette and dolo. Bring back shea butter (cosmetic or cooking)."),
    "BG": ("Yaourt, roses et rakija. Rapportez de l'huile de rose ou de la confiture.", "Yogurt, roses and rakija. Bring back rose oil or jam."),
    "BH": ("Dattes et perles. Rapportez des dattes farcies. Et des photos des mosquées.", "Dates and pearls. Bring back stuffed dates. And mosque photos."),
    "BI": ("Café et lac Tanganyika. Rapportez du café burundais (très sous-estimé).", "Coffee and Lake Tanganyika. Bring back Burundi coffee (underrated)."),
    "BJ": ("Pâte d'arachide et côte. Rapportez du gari ou du sodabi si vous aimez.", "Peanut paste and coast. Bring back gari or sodabi if you're into it."),
    "BN": ("Ambil (gâteau) et forêt. Rapportez des gâteaux locaux pour le bureau.", "Ambil cake and forest. Bring back local cakes for the office."),
    "BO": ("Salteña, altitude et lama. Rapportez du chocolat ou de la quinoa.", "Salteña, altitude and llama. Bring back chocolate or quinoa."),
    "BR": ("Feijoada, caipirinha et Christ. Rapportez de la cachaça ou du guaraná.", "Feijoada, caipirinha and Christ. Bring back cachaça or guaraná."),
    "BS": ("Conch, rhum et plage. Rapportez du rhum ou des épices à conch.", "Conch, rum and beach. Bring back rum or conch spices."),
    "BT": ("Piment partout et dzongs. Rapportez du thé ou du fromage de yak (séché).", "Chilli everywhere and dzongs. Bring back tea or dried yak cheese."),
    "BW": ("Safari et braai. Rapportez rien d'animal — juste des photos et du mopane worm (si vous osez).", "Safari and braai. Bring back nothing animal — just photos and mopane worm (if you dare)."),
    "BY": ("Pommes de terre et bania. Rapportez de la vodka locale ou du chocolat.", "Potatoes and bania. Bring back local vodka or chocolate."),
    "BZ": ("Rum, récif et jungle. Rapportez du rhum One Barrel ou du hot sauce.", "Rum, reef and jungle. Bring back One Barrel rum or hot sauce."),
    "CA": ("Sirop d'érable, poutine et « sorry ». Rapportez du sirop. Ou du whisky canadien.", "Maple syrup, poutine and 'sorry'. Bring back syrup. Or Canadian whisky."),
    "CD": ("Congo : fufu, pondu et café. Rapportez du café si vous trouvez.", "Congo: fufu, pondu and coffee. Bring back coffee if you find it."),
    "CF": ("Manioc et forêt. Rapportez du miel sauvage si disponible.", "Cassava and forest. Bring back wild honey if available."),
    "CG": ("Poulet moambe et forêt. Rapportez du piment ou du café.", "Poulet moambe and forest. Bring back chilli or coffee."),
    "CH": ("Fondue, chocolat et couteau suisse. Rapportez du chocolat. Ou un couteau. Ou les deux.", "Fondue, chocolate and Swiss army knife. Bring back chocolate. Or a knife. Or both."),
    "CI": ("Alloco, attiéké et zouk. Rapportez du cacao ou du café.", "Alloco, attiéké and zouk. Bring back cocoa or coffee."),
    "CL": ("Pisco, avocat et désert. Rapportez du pisco ou du vin. Et des alfajores.", "Pisco, avocado and desert. Bring back pisco or wine. And alfajores."),
    "CM": ("Ndolé, plantain et bière. Rapportez du café ou du cacao.", "Ndolé, plantain and beer. Bring back coffee or cocoa."),
    "CN": ("Thé, canard laqué et Grande Muraille. Rapportez du thé, des épices ou de la soie.", "Tea, Peking duck and Great Wall. Bring back tea, spices or silk."),
    "CO": ("Café, arepas et Shakira. Rapportez du café. Vraiment. Et peut-être de l'aguardiente.", "Coffee, arepas and Shakira. Bring back coffee. Seriously. And maybe aguardiente."),
    "CR": ("Gallo pinto, café et pura vida. Rapportez du café et du cacao.", "Gallo pinto, coffee and pura vida. Bring back coffee and cocoa."),
    "CU": ("Mojito, cigare et vieille Havane. Rapportez du rhum (et des cigares si douane OK).", "Mojito, cigar and old Havana. Bring back rum (and cigars if customs allow)."),
    "CV": ("Cachupa et grogue. Rapportez du grogue. Et du thon en conserve local (sérieux).", "Cachupa and grogue. Bring back grogue. And local tinned tuna (seriously)."),
    "CY": ("Halloumi, mezze et mer. Rapportez du halloumi (sous vide) ou de l'huile.", "Halloumi, mezze and sea. Bring back halloumi (vacuum-packed) or oil."),
    "CZ": ("Bière, trdelník et châteaux. Rapportez de la Becherovka ou du fromage olomoucké.", "Beer, trdelník and castles. Bring back Becherovka or olomoucké cheese."),
    "DE": ("Bratwurst, bière et ponctualité. Rapportez du Lebkuchen ou du Haribo (inventé là-bas).", "Bratwurst, beer and punctuality. Bring back Lebkuchen or Haribo (invented there)."),
    "DJ": ("Lac Assal et mer. Rapportez du sel du lac si vous y allez.", "Lake Assal and sea. Bring back lake salt if you go."),
    "DK": ("Hygge, smørrebrød et vélo. Rapportez des licorice ou du fromage danois.", "Hygge, smørrebrød and bikes. Bring back liquorice or Danish cheese."),
    "DM": ("Fruits tropicaux et cascades. Rapportez du rhum ou du cacao.", "Tropical fruit and waterfalls. Bring back rum or cocoa."),
    "DO": ("Mangú, rhum et bachata. Rapportez du Mamajuana ou du rhum Brugal.", "Mangú, rum and bachata. Bring back Mamajuana or Brugal rum."),
    "DZ": ("Couscous, thé à la menthe et Sahara. Rapportez des dattes ou des épices.", "Couscous, mint tea and Sahara. Bring back dates or spices."),
    "EC": ("Ceviche, quinoa et Galápagos. Rapportez du chocolat ou du café. Et des photos d'iguanes.", "Ceviche, quinoa and Galápagos. Bring back chocolate or coffee. And iguana photos."),
    "EE": ("Sauna, pain noir et Tallinn. Rapportez du Vana Tallinn ou du chocolat Kalev.", "Sauna, black bread and Tallinn. Bring back Vana Tallinn or Kalev chocolate."),
    "EG": ("Koshari, thé et pyramides. Rapportez des épices ou du coton égyptien.", "Koshari, tea and pyramids. Bring back spices or Egyptian cotton."),
    "ER": ("Café et mer Rouge. Rapportez du café érythréen si vous en trouvez.", "Coffee and Red Sea. Bring back Eritrean coffee if you find it."),
    "ES": ("Tapas, jamón et siesta. Rapportez du jamón (sous vide) ou du turrón. Ou les deux.", "Tapas, jamón and siesta. Bring back jamón (vacuum-packed) or turrón. Or both."),
    "ET": ("Café, injera et berceau de l'humanité. Rapportez du café. Le meilleur au monde, selon certains.", "Coffee, injera and cradle of humankind. Bring back coffee. Best in the world, some say."),
    "FI": ("Sauna, réglisse salée et Nokia. Rapportez du Fazer (chocolat) ou de la salmiakki.", "Sauna, salty liquorice and Nokia. Bring back Fazer chocolate or salmiakki."),
    "FJ": ("Lovo, kava et plongée. Rapportez du kava (vérifiez douanes) ou des perles.", "Lovo, kava and diving. Bring back kava (check customs) or pearls."),
    "FR": ("Fromage, vin et grève. Rapportez du fromage (dur à garder) ou du vin. Ou un saucisson.", "Cheese, wine and strike. Bring back cheese (tricky to keep) or wine. Or saucisson."),
    "GA": ("Poulet nyembwe et forêt. Rapportez du café ou du cacao.", "Poulet nyembwe and forest. Bring back coffee or cocoa."),
    "GB": ("Fish & chips, thé et queue. Rapportez du thé, des biscuits ou du cheddar.", "Fish & chips, tea and queueing. Bring back tea, biscuits or cheddar."),
    "UK": ("Fish & chips, thé et queue. Rapportez du thé, des biscuits ou du cheddar.", "Fish & chips, tea and queueing. Bring back tea, biscuits or cheddar."),
    "GD": ("Épices, rhum et plage. Rapportez du rhum ou du chocolat (cacao local).", "Spices, rum and beach. Bring back rum or chocolate (local cocoa)."),
    "GE": ("Vin, khachapuri et montagnes. Rapportez du vin géorgien. Et du churchkhela.", "Wine, khachapuri and mountains. Bring back Georgian wine. And churchkhela."),
    "GH": ("Jollof, fufu et cacao. Rapportez du cacao ou du kente (tissu).", "Jollof, fufu and cocoa. Bring back cocoa or kente cloth."),
    "GM": ("Domoda et côte. Rapportez du cacahuète (beurre ou graines).", "Domoda and coast. Bring back peanut butter or seeds."),
    "GN": ("Riz jollof et musique. Rapportez du café ou des tissus.", "Jollof rice and music. Bring back coffee or fabrics."),
    "GQ": ("Chocolat et pétrole. Rapportez du cacao équatorial si vous trouvez.", "Chocolate and oil. Bring back Equatorial cocoa if you find it."),
    "GR": ("Ouzo, feta et îles. Rapportez de l'huile d'olive, du miel ou de l'ouzo.", "Ouzo, feta and islands. Bring back olive oil, honey or ouzo."),
    "GT": ("Pepian, café et Tikal. Rapportez du café. Et du rum Zacapa si la valise le permet.", "Pepian, coffee and Tikal. Bring back coffee. And Zacapa rum if the bag allows."),
    "GW": ("Caldou et côte. Rapportez du cajou ou du rhum.", "Caldou and coast. Bring back cashews or rum."),
    "GY": ("Rum, pepperpot et jungle. Rapportez du rhum Demerara ou du El Dorado.", "Rum, pepperpot and jungle. Bring back Demerara or El Dorado rum."),
    "HN": ("Baleada, café et ruines. Rapportez du café ou du rhum.", "Baleada, coffee and ruins. Bring back coffee or rum."),
    "HR": ("Peka, truffe et Adriatique. Rapportez de l'huile, de la truffe ou de la rakija.", "Peka, truffle and Adriatic. Bring back oil, truffle or rakija."),
    "HT": ("Griot, rhum et compas. Rapportez du rhum Barbancourt. Incontournable.", "Griot, rum and compas. Bring back Barbancourt rum. A must."),
    "HU": ("Goulash, paprika et bains. Rapportez du paprika (en tube ou poudre) ou du Tokaji.", "Goulash, paprika and baths. Bring back paprika (tube or powder) or Tokaji."),
    "ID": ("Nasi goreng, satay et îles. Rapportez du kopi luwak (si éthique) ou des épices.", "Nasi goreng, satay and islands. Bring back kopi luwak (if ethical) or spices."),
    "IE": ("Guinness, fish & chips et pluie. Rapportez du whiskey irlandais ou du cheddar.", "Guinness, fish & chips and rain. Bring back Irish whiskey or cheddar."),
    "IL": ("Falafel, hummus et mer. Rapportez du zaatar, des dattes ou du vin.", "Falafel, hummus and sea. Bring back zaatar, dates or wine."),
    "IN": ("Curry, chai et chaos organisé. Rapportez des épices, du thé ou des saris.", "Curry, chai and organised chaos. Bring back spices, tea or saris."),
    "IQ": ("Kebab, thé et histoire. Rapportez des dattes ou des épices (selon contexte).", "Kebab, tea and history. Bring back dates or spices (depending on context)."),
    "IR": ("Saffron, pistache et thé. Rapportez du safran, des pistaches ou de la confiture de rose.", "Saffron, pistachio and tea. Bring back saffron, pistachios or rose jam."),
    "IS": ("Skyr, hot dog et geysers. Rapportez du skyr (en poudre) ou du sel noir.", "Skyr, hot dog and geysers. Bring back skyr (powder) or black salt."),
    "IT": ("Pizza, pasta et gesticulation. Rapportez du parmesan (sous vide), de l'huile ou du limoncello.", "Pizza, pasta and hand gestures. Bring back parmesan (vacuum-packed), oil or limoncello."),
    "JM": ("Jerk chicken, reggae et plage. Rapportez du rhum jamaïcain ou du Blue Mountain coffee.", "Jerk chicken, reggae and beach. Bring back Jamaican rum or Blue Mountain coffee."),
    "JO": ("Mansaf, thé et Pétra. Rapportez des dattes, du zaatar ou de la céramique.", "Mansaf, tea and Petra. Bring back dates, zaatar or ceramics."),
    "JP": ("Ramen, sushi et convenance. Rapportez du whisky japonais, du matcha ou des Kit Kat bizarres.", "Ramen, sushi and convenience. Bring back Japanese whisky, matcha or weird Kit Kats."),
    "KE": ("Nyama choma, safari et thé. Rapportez du café ou du thé. Et des photos de gnous.", "Nyama choma, safari and tea. Bring back coffee or tea. And wildebeest photos."),
    "KG": ("Laghman, kumis et montagnes. Rapportez du miel ou du felt. Oui, du feutre.", "Laghman, kumis and mountains. Bring back honey or felt. Yes, felt."),
    "KH": ("Amok, temples et tuk-tuk. Rapportez du poivre de Kampot ou de la soie.", "Amok, temples and tuk-tuk. Bring back Kampot pepper or silk."),
    "KM": ("Langouste et îles. Rapportez du ylang-ylang ou de la vanille.", "Lobster and islands. Bring back ylang-ylang or vanilla."),
    "KN": ("Rum et cricket. Rapportez du rhum ou des épices.", "Rum and cricket. Bring back rum or spices."),
    "KP": ("Contexte particulier. Un jour, on pourra rapporter du kimchi de Pyongyang.", "Specific context. One day we'll bring back Pyongyang kimchi."),
    "KR": ("Kimchi, K-pop et convenience stores. Rapportez du soju, du ginseng ou des snacks bizarres.", "Kimchi, K-pop and convenience stores. Bring back soju, ginseng or weird snacks."),
    "KW": ("Machboos et tours. Rapportez des dattes ou du parfum (souks).", "Machboos and towers. Bring back dates or perfume (souks)."),
    "KZ": ("Beshbarmak et steppes. Rapportez du miel ou du kurt (fromage séché).", "Beshbarmak and steppes. Bring back honey or kurt (dried cheese)."),
    "LA": ("Larb, café et Mékong. Rapportez du café lao ou de la soie.", "Larb, coffee and Mekong. Bring back Lao coffee or silk."),
    "LB": ("Mezze, arak et cèdres. Rapportez du zaatar, de l'huile ou de l'arak.", "Mezze, arak and cedars. Bring back zaatar, oil or arak."),
    "LC": ("Rum, bananes et Pitons. Rapportez du rhum ou du cacao.", "Rum, bananas and Pitons. Bring back rum or cocoa."),
    "LI": ("Fromage et ski. Rapportez du fromage (petit pays, grande fromagerie).", "Cheese and ski. Bring back cheese (small country, big dairy)."),
    "LK": ("Curry, thé et plages. Rapportez du thé Ceylan ou des épices.", "Curry, tea and beaches. Bring back Ceylon tea or spices."),
    "LR": ("Jollof et côte. Rapportez du café ou du cacao.", "Jollof and coast. Bring back coffee or cocoa."),
    "LS": ("Braai et montagnes. Rapportez du mohair ou du chapeau basotho.", "Braai and mountains. Bring back mohair or a Basotho hat."),
    "LT": ("Cepelinai et forêt. Rapportez du fromage ou de l'ambre (côte).", "Cepelinai and forest. Bring back cheese or amber (coast)."),
    "LU": ("Riesling, Gromperekichelcher et banques. Rapportez du vin ou du moutarde de Luxembourg.", "Riesling, Gromperekichelcher and banks. Bring back wine or Luxembourg mustard."),
    "LV": ("Riga black balsam et Art nouveau. Rapportez du Balsam ou du fromage caramélisé.", "Riga black balsam and Art Nouveau. Bring back Balsam or caramelised cheese."),
    "LY": ("Thé et désert. Rapportez des dattes ou du miel (selon contexte).", "Tea and desert. Bring back dates or honey (depending on context)."),
    "MA": ("Tagine, thé à la menthe et souks. Rapportez des épices, une lampe ou du cuir.", "Tagine, mint tea and souks. Bring back spices, a lamp or leather."),
    "MC": ("Barbajuan et yachts. Rapportez du fromage de chèvre ou du pain de Monaco.", "Barbajuan and yachts. Bring back goat cheese or Monaco bread."),
    "MD": ("Mamaliga, vin et grottes. Rapportez du vin moldave (sous-estimé) ou du fromage.", "Mamaliga, wine and caves. Bring back Moldovan wine (underrated) or cheese."),
    "ME": ("Rakija, cevapi et Adriatique. Rapportez de la rakija ou du fromage njeguški.", "Rakija, cevapi and Adriatic. Bring back rakija or njeguški cheese."),
    "MG": ("Romazava, lémuriens et vanille. Rapportez de la vanille. La meilleure au monde.", "Romazava, lemurs and vanilla. Bring back vanilla. Best in the world."),
    "MK": ("Ajvar, rakija et lac Ohrid. Rapportez de l'ajvar (tube) ou du fromage kashkaval.", "Ajvar, rakija and Lake Ohrid. Bring back ajvar (tube) or kashkaval cheese."),
    "ML": ("Thé touareg et Sahara. Rapportez du bogolan (tissu) ou des dattes.", "Touareg tea and Sahara. Bring back bogolan cloth or dates."),
    "MM": ("Laphet (thé fermenté) et pagodes. Rapportez du laphet ou de la soie.", "Laphet (fermented tea) and pagodas. Bring back laphet or silk."),
    "MN": ("Airag, viande et steppes. Rapportez du cachemire ou du fromage séché (si vous osez).", "Airag, meat and steppes. Bring back cashmere or dried cheese (if you dare)."),
    "MR": ("Thé et désert. Rapportez des dattes ou du poisson séché.", "Tea and desert. Bring back dates or dried fish."),
    "MT": ("Pastizzi, fenek et Méditerranée. Rapportez du vin ou du kunserva (concentré tomate).", "Pastizzi, fenek and Mediterranean. Bring back wine or kunserva (tomato paste)."),
    "MU": ("Dholl puri, rhum et lagons. Rapportez du rhum ou de la vanille.", "Dholl puri, rum and lagoons. Bring back rum or vanilla."),
    "MV": ("Mas huni, plongée et atolls. Rapportez du thon séché (mas) ou des perles.", "Mas huni, diving and atolls. Bring back dried tuna (mas) or pearls."),
    "MW": ("Nsima, lac Malawi et thé. Rapportez du thé ou du café.", "Nsima, Lake Malawi and tea. Bring back tea or coffee."),
    "MX": ("Tacos, mezcal et Frida. Rapportez du mezcal, de la sauce Valentina ou du chocolat.", "Tacos, mezcal and Frida. Bring back mezcal, Valentina sauce or chocolate."),
    "MY": ("Nasi lemak, laksa et tours. Rapportez du teh tarik (en poudre), du white coffee ou des durians (en soute, emballés).", "Nasi lemak, laksa and towers. Bring back teh tarik (powder), white coffee or durians (hold, wrapped)."),
    "MZ": ("Piri-piri, prawns et plages. Rapportez du piri-piri ou des noix de cajou.", "Piri-piri, prawns and beaches. Bring back piri-piri or cashews."),
    "NA": ("Braai, désert et safari. Rapportez du biltong (vérifiez douanes) ou des pierres semi-précieuses.", "Braai, desert and safari. Bring back biltong (check customs) or semi-precious stones."),
    "NE": ("Thé et Sahara. Rapportez des dattes ou du cuir.", "Tea and Sahara. Bring back dates or leather."),
    "NG": ("Jollof, pepper soup et mégapole. Rapportez du cacao, des épices ou de l'ankara (tissu).", "Jollof, pepper soup and megacity. Bring back cocoa, spices or ankara cloth."),
    "NI": ("Gallo pinto, nacatamal et volcans. Rapportez du café ou du rhum Flor de Caña.", "Gallo pinto, nacatamal and volcanoes. Bring back coffee or Flor de Caña rum."),
    "NL": ("Stroopwafel, fromage et vélos. Rapportez des stroopwafels, du Gouda ou du genever.", "Stroopwafel, cheese and bikes. Bring back stroopwafels, Gouda or genever."),
    "NO": ("Brunost, saumon et fjords. Rapportez du brunost (fromage caramel) ou du aquavit.", "Brunost, salmon and fjords. Bring back brunost (caramel cheese) or aquavit."),
    "NP": ("Dal bhat, thé et Himalaya. Rapportez du thé, des épices ou du pashmina.", "Dal bhat, tea and Himalayas. Bring back tea, spices or pashmina."),
    "NZ": ("Pavlova, fish & chips et moutons. Rapportez du Manuka honey ou du vin. Et des photos de hobbits.", "Pavlova, fish & chips and sheep. Bring back Manuka honey or wine. And hobbit photos."),
    "OM": ("Dates, encens et désert. Rapportez de l'encens (frankincense), des dattes ou du halwa.", "Dates, incense and desert. Bring back frankincense, dates or halwa."),
    "PA": ("Ceviche, sancocho et canal. Rapportez du café Geisha ou du rhum Seco.", "Ceviche, sancocho and canal. Bring back Geisha coffee or Seco rum."),
    "PE": ("Ceviche, pisco et Machu Picchu. Rapportez du pisco, des épices ou de l'alpaga.", "Ceviche, pisco and Machu Picchu. Bring back pisco, spices or alpaca."),
    "PG": ("Mumu, café et jungle. Rapportez du café ou du cacao.", "Mumu, coffee and jungle. Bring back coffee or cocoa."),
    "PH": ("Adobo, halo-halo et 7000 îles. Rapportez du mangoustan (saison) ou du rhum Tanduay.", "Adobo, halo-halo and 7000 islands. Bring back mangosteen (season) or Tanduay rum."),
    "PK": ("Biryani, chai et montagnes. Rapportez des épices, du thé ou du tissu.", "Biryani, chai and mountains. Bring back spices, tea or fabric."),
    "PL": ("Pierogi, vodka et châteaux. Rapportez de la vodka, du fromage oscypek ou du pain d'épices.", "Pierogi, vodka and castles. Bring back vodka, oscypek cheese or gingerbread."),
    "PT": ("Pastéis de nata, bacalhau et tramway. Rapportez du porto, des pastéis (emballés) ou de l'huile.", "Pastéis de nata, bacalhau and tram. Bring back port, pastéis (packaged) or oil."),
    "PY": ("Tereré, chipa et chutes. Rapportez du tereré (maté froid) ou du chipa.", "Tereré, chipa and waterfalls. Bring back tereré (cold mate) or chipa."),
    "QA": ("Machboos et tours. Rapportez des dattes ou du parfum.", "Machboos and towers. Bring back dates or perfume."),
    "RO": ("Sarmale, mamaliga et Dracula. Rapportez de la tuica, du fromage ou du miel.", "Sarmale, mamaliga and Dracula. Bring back tuica, cheese or honey."),
    "RS": ("Ćevapi, rakija et Belgrade. Rapportez de la rakija ou du kajmak.", "Ćevapi, rakija and Belgrade. Bring back rakija or kajmak."),
    "RU": ("Vodka, blinis et froid. Rapportez de la vodka, du caviar (réglementé) ou du chocolat.", "Vodka, blinis and cold. Bring back vodka, caviar (regulated) or chocolate."),
    "RW": ("Brochettes, café et gorilles. Rapportez du café. L'un des meilleurs d'Afrique.", "Brochettes, coffee and gorillas. Bring back coffee. One of Africa's best."),
    "SA": ("Kabsa, dates et désert. Rapportez des dattes, du café arabe ou du parfum.", "Kabsa, dates and desert. Bring back dates, Arabic coffee or perfume."),
    "SB": ("Poi, coco et plongée. Rapportez du cacao ou des coquillages (vérifiez).", "Poi, coconut and diving. Bring back cocoa or shells (check)."),
    "SC": ("Rougaille, rhum et plages. Rapportez du rhum ou de la vanille.", "Rougaille, rum and beaches. Bring back rum or vanilla."),
    "SD": ("Ful, thé et Nil. Rapportez des épices ou du sésame (tahini).", "Ful, tea and Nile. Bring back spices or sesame (tahini)."),
    "SE": ("Fika, köttbullar et IKEA. Rapportez du surströmming (blague) ou du chocolat Marabou.", "Fika, köttbullar and IKEA. Bring back surströmming (joke) or Marabou chocolate."),
    "SG": ("Laksa, hawker et Marina Bay. Rapportez du teh, du white pepper crab (en poudre) ou des snacks.", "Laksa, hawker and Marina Bay. Bring back teh, white pepper (powder) or snacks."),
    "SI": ("Kranjska klobasa, vin et lac Bled. Rapportez du vin, du miel ou de la potica.", "Kranjska klobasa, wine and Lake Bled. Bring back wine, honey or potica."),
    "SK": ("Bryndza, slivovitz et châteaux. Rapportez de la slivovitz ou du fromage de brebis.", "Bryndza, slivovitz and castles. Bring back slivovitz or sheep cheese."),
    "SL": ("Jollof et côte. Rapportez du cacao ou du café.", "Jollof and coast. Bring back cocoa or coffee."),
    "SM": ("Piadina et Titano. Rapportez du fromage ou du vin (micro-État, grande table).", "Piadina and Titano. Bring back cheese or wine (microstate, great food)."),
    "SN": ("Thiéboudiène, bissap et teranga. Rapportez du bissap (sirop), des épices ou du thé kinkeliba.", "Thiéboudiène, bissap and teranga. Bring back bissap (syrup), spices or kinkeliba tea."),
    "SO": ("Contexte fragile. Un jour : thé, bananes et plages.", "Fragile context. One day: tea, bananas and beaches."),
    "SR": ("Roti, pomme cythère et forêt. Rapportez du rhum ou des épices.", "Roti, pomme cythère and forest. Bring back rum or spices."),
    "SS": ("Kisra et Nil. Rapportez du café ou du miel (selon contexte).", "Kisra and Nile. Bring back coffee or honey (depending on context)."),
    "ST": ("Calulu et cacao. Rapportez du cacao ou du café.", "Calulu and cocoa. Bring back cocoa or coffee."),
    "SV": ("Pupusas, café et volcans. Rapportez du café ou du rhum.", "Pupusas, coffee and volcanoes. Bring back coffee or rum."),
    "SY": ("Contexte particulier. Mezze et histoire attendront.", "Specific context. Mezze and history will wait."),
    "SZ": ("Sishwala, safari et culture. Rapportez du miel ou de l'artisanat.", "Sishwala, safari and culture. Bring back honey or crafts."),
    "TD": ("La boule et Sahara. Rapportez des dattes ou du miel.", "La boule and Sahara. Bring back dates or honey."),
    "TG": ("Fufu, côte et vaudou. Rapportez du cacao ou du café.", "Fufu, coast and voodoo. Bring back cocoa or coffee."),
    "TH": ("Pad thai, mango sticky rice et temples. Rapportez du curry paste (en tube) ou de la soie.", "Pad thai, mango sticky rice and temples. Bring back curry paste (tube) or silk."),
    "TJ": ("Plov, thé et montagnes. Rapportez des noix, du miel ou du tissu brodé.", "Plov, tea and mountains. Bring back nuts, honey or embroidered cloth."),
    "TL": ("Café et côte. Rapportez du café timorais (sous-estimé).", "Coffee and coast. Bring back Timorese coffee (underrated)."),
    "TM": ("Manti, tapis et désert. Rapportez un tapis (petit) ou des melons séchés.", "Manti, carpets and desert. Bring back a (small) carpet or dried melons."),
    "TN": ("Couscous, harissa et médinas. Rapportez de l'harissa, des dattes ou de la céramique.", "Couscous, harissa and medinas. Bring back harissa, dates or ceramics."),
    "TO": ("Lu, umu et plages. Rapportez du tapa (tissu) ou de la vanille.", "Lu, umu and beaches. Bring back tapa cloth or vanilla."),
    "TR": ("Kebab, baklava et Bosphore. Rapportez du loukoum, des épices ou du café turc.", "Kebab, baklava and Bosphorus. Bring back lokum, spices or Turkish coffee."),
    "TT": ("Doubles, roti et steel pan. Rapportez du rhum Angostura ou des épices.", "Doubles, roti and steel pan. Bring back Angostura rum or spices."),
    "TV": ("Palusami et atolls. Rapportez de l'artisanat ou du poisson séché.", "Palusami and atolls. Bring back crafts or dried fish."),
    "TW": ("Bubble tea, night markets et montagnes. Rapportez du thé, des gâteaux d'ananas ou des snacks.", "Bubble tea, night markets and mountains. Bring back tea, pineapple cakes or snacks."),
    "TZ": ("Nyama choma, Zanzibar et Kilimandjaro. Rapportez du café, des épices ou du kitenge.", "Nyama choma, Zanzibar and Kilimanjaro. Bring back coffee, spices or kitenge."),
    "UA": ("Borscht, vodka et steppes. Rapportez du chocolat, de la vodka ou du miel.", "Borscht, vodka and steppes. Bring back chocolate, vodka or honey."),
    "UG": ("Matoke, Rolex (sandwich) et gorilles. Rapportez du café ou du vanille.", "Matoke, Rolex (sandwich) and gorillas. Bring back coffee or vanilla."),
    "US": ("Portions XXL, brunch et États variés. Rapportez du maple syrup (si Nord), du hot sauce ou du bourbon.", "XXL portions, brunch and varied states. Bring back maple syrup (if North), hot sauce or bourbon."),
    "UY": ("Asado, mate et plages. Rapportez du dulce de leche, du vin tannat ou du mate.", "Asado, mate and beaches. Bring back dulce de leche, tannat wine or mate."),
    "UZ": ("Plov, thé et Route de la soie. Rapportez des tapis (petits), du miel ou des épices.", "Plov, tea and Silk Road. Bring back (small) carpets, honey or spices."),
    "VC": ("Rum et plages. Rapportez du rhum ou du breadfruit (en conserve).", "Rum and beaches. Bring back rum or breadfruit (tinned)."),
    "VE": ("Arepas, cachapa et Angel Falls. Rapportez du café ou du cacao (selon contexte).", "Arepas, cachapa and Angel Falls. Bring back coffee or cocoa (depending on context)."),
    "VN": ("Pho, banh mi et baie d'Halong. Rapportez du café (weasel si vous osez), de la sauce nuoc mam ou de la soie.", "Pho, banh mi and Halong Bay. Bring back coffee (weasel if you dare), nuoc mam or silk."),
    "VU": ("Lap lap, kava et volcans. Rapportez du kava (vérifiez douanes) ou du bœuf séché.", "Lap lap, kava and volcanoes. Bring back kava (check customs) or dried beef."),
    "WS": ("Umu, kava et plages. Rapportez de la vanille ou du tapa.", "Umu, kava and beaches. Bring back vanilla or tapa."),
    "YE": ("Contexte difficile. Le miel yéménite attendra.", "Difficult context. Yemeni honey will wait."),
    "ZA": ("Braai, vin et safari. Rapportez du vin, du biltong (vérifiez) ou du rooibos.", "Braai, wine and safari. Bring back wine, biltong (check) or rooibos."),
    "ZM": ("Nshima, chutes Victoria et bière. Rapportez du café ou du miel.", "Nshima, Victoria Falls and beer. Bring back coffee or honey."),
    "ZW": ("Sadza, safari et pierres. Rapportez du café, du thé ou de l'artisanat.", "Sadza, safari and stones. Bring back coffee, tea or crafts."),
}


def get_tips_for_code(code, generic_index):
    """Return {"fr": "...", "en": "..."} for a country code."""
    code = (code or "").strip().upper()[:2]
    if code in SPECIFIC_TIPS:
        fr, en = SPECIFIC_TIPS[code]
        return {"fr": fr, "en": en}
    idx = generic_index % len(GENERIC_TIPS)
    fr, en = GENERIC_TIPS[idx]
    return {"fr": fr, "en": en}


def build_tips_json(codes):
    """Build a dict code -> {fr, en} for all given codes."""
    out = {}
    for i, code in enumerate(codes):
        c = (code or "").strip().upper()[:2]
        if not c:
            continue
        out[c] = get_tips_for_code(c, hash(code) % (10 ** 6))
    return out
